### ISSUE TITLE
Crash on login

### ISSUE THREAD

**Issue by latonita** [vman/spfx-extentions-cli#3]
Hi, I understand this tool might be quite outdated :) but just in case you can take a look.
It crashes on start, when i try to connect. Any ideas?

```
C:\Playground\sp_management\spfx-manage-extension-cli>spfx-ext --connect "https://ourcompany.sharepoint.com"
C:\Users\latonita\AppData\Roaming\npm\node_modules\spfx-extensions-cli\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\OnDemand.js:83
        let cookiesJson = cookieData[1].split(';#;');
                                    ^

TypeError: Cannot read property '1' of null
    at OnDemand.saveAuthData (C:\Users\latonita\AppData\Roaming\npm\node_modules\spfx-extensions-cli\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\OnDemand.js:83:37)
    at OnDemand.getAuth (C:\Users\latonita\AppData\Roaming\npm\node_modules\spfx-extensions-cli\node_modules\node-sp-auth\lib\src\auth\resolvers\ondemand\OnDemand.js:39:28)
    at Object.getAuth (C:\Users\latonita\AppData\Roaming\npm\node_modules\spfx-extensions-cli\node_modules\node-sp-auth\lib\src\index.js:8:76)
    at Object.<anonymous> (C:\Users\latonita\AppData\Roaming\npm\node_modules\spfx-extensions-cli\dist\index.js:94:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

```

**Comment by devanshuGit** [comment]
is it still supported or we have alternative to work with SPFX solutions like similar commands in Office 365 cli?

**Comment by jakemannion** [comment]
I am wondering the same. Can't connect either.
![image](https://user-images.githubusercontent.com/41285392/97093511-58787600-1601-11eb-8cca-ee57c2896332.png)

**Comment by vman** [comment]
Hi all, I am no longer actively working on this mainly because the Microsoft 365 CLI (formerly Office 365 CLI) is a better alternative to manage the SPFx extensions among many other things. 

Here is a blogpost which might help you: https://sharepoint.handsontek.net/2018/02/11/mange-spfx-extensions-from-macos-with-office-365-cli/

and the customaction docs for the M365 CLI: https://pnp.github.io/cli-microsoft365/cmd/spo/customaction/customaction-add/

I will archive this repository now.
